version: "2"
services:
    app:
        build: ./app
        ports:
            - "5000:5000"
        container_name: flask-app
        links: 
            - db
        environment:
            FLASK_DEBUG: 'True'
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: root
            DB_PWD: root
            DB_NAME: nodes
    db:
        image: mysql:5.7
        ports:
            - "32000:3306"
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db/tables.sql:/docker-entrypoint-initdb.d/1.sql
            - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql